# 做法 B：觸發程式只做建置 + 推送 + 部署（不帶金鑰、不帶 Cloud SQL 連線）
# 金鑰、DATABASE_URL、Cloud SQL 連線請在 Cloud Run 服務裡設一次，之後部署會保留

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--no-cache"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:latest"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:latest"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-east1
  _REPO: linebot
  _IMAGE: linebot
  _SERVICE: songfu-line-bot
